# Generated by Django 5.1.4 on 2024-12-24 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('series_order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('book_status', models.CharField(choices=[('TR', 'To Read'), ('TA', 'To Acquire'), ('F', 'Finished'), ('N4', 'Not For Me')], max_length=2)),
                ('genre', models.CharField(choices=[('F', 'Fiction'), ('SF', 'Science Fiction'), ('FA', 'Fantasy'), ('M', 'Mystery'), ('H', 'History'), ('O', 'Other')], max_length=2)),
                ('book_type', models.CharField(choices=[('P', 'Paper'), ('K', 'Kindle'), ('A', 'Audible')], max_length=1)),
                ('favorite', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='books.author')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='books.series')),
            ],
        ),
    ]
